default: &default
  adapter: mysql
  encoding: utf8
  username: <%= ENV['DB_USER'] || "root" %>
  password: <%= ENV['DB_PASS'] || "" %>
  host: <%= ENV['DB_HOST'] || "127.0.0.1" %>
  port: <%= ENV['DB_PORT'] || "3306" %>
  pool: <%= ENV['DB_POOL_SIZE'] || 5 %>

development:
  <<: *default
  database: <%= ENV['DEV_DB_NAME'] || "photoalbum_dev" %>

production:
  <<: *default
  database: <%= ENV['PROD_DB_NAME'] || "photoalbum_local" %>

test:
  <<: *default
  database: <%= ENV['TEST_DB_NAME'] || "photoalbum_test" %>
